//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student.ModelStu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string StudentGuid { get; set; }
        public string LoginId { get; set; }
        public string LoginPwd { get; set; }
        public int UserStateId { get; set; }
        public string ClassGuid { get; set; }
        public string StudentNO { get; set; }
        public string StudentName { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
