//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student.ModelStu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public string TeacherGUID { get; set; }
        public string LoginId { get; set; }
        public string LoginPwd { get; set; }
        public int UserStateId { get; set; }
        public string TeacherName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string SubjectGUID { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
